"""Smoke tests for the file readers — no LLM, no network."""
from pathlib import Path

import pytest

from workflow_doc_agent.readers import (
    discover_workflow_files,
    read_excel_file,
    read_python_file,
)

SAMPLES = Path(__file__).resolve().parents[1] / "samples" / "revenue_forecast"


def test_discover_workflow_files() -> None:
    py, xlsx = discover_workflow_files(SAMPLES)
    assert any(p.name == "forecast_pipeline.py" for p in py)
    # Excel file is generated by running the pipeline; may or may not exist
    # in CI before the build step. The discover function should still work.
    assert isinstance(xlsx, list)


def test_read_python_file() -> None:
    ctx = read_python_file(SAMPLES / "forecast_pipeline.py")
    assert "load_actuals" in ctx.functions
    assert any("openpyxl" in i for i in ctx.imports)
    assert "MonthlyActual" in ctx.classes
    assert ctx.source.startswith('"""Monthly revenue forecast pipeline')


def test_read_excel_file_if_present() -> None:
    xlsx_path = SAMPLES / "monthly_revenue.xlsx"
    if not xlsx_path.exists():
        pytest.skip("workbook not generated yet; run the sample pipeline first")
    ctx = read_excel_file(xlsx_path)
    assert "Actuals" in ctx.sheets
    assert "Forecast" in ctx.sheets
    assert "Sensitivity" in ctx.sheets
