"""Pydantic schemas for every output stage of the agent.

Stages:
1. PythonFileSummary  — what the .py file does (LLM-extracted from source + AST).
2. ExcelFileSummary   — structure of the .xlsx (LLM-extracted from sheet/column data).
3. WorkflowSummary    — combined purpose + clarifying questions for the human owner.
4. WorkflowAnswers    — the human's answers (CLI-collected).
5. FinalDoc           — the rendered markdown documentation, fully validated.
"""
from typing import Literal

from pydantic import BaseModel, Field


class PythonFileSummary(BaseModel):
    """What the .py file does, in structured form."""

    one_line_purpose: str = Field(
        ..., description="A single sentence describing what this script does."
    )
    inputs: list[str] = Field(
        default_factory=list,
        description="Files, env vars, or arguments this script reads.",
    )
    outputs: list[str] = Field(
        default_factory=list,
        description="Files, tables, or stdout this script writes.",
    )
    dependencies: list[str] = Field(
        default_factory=list,
        description="Top-level imports and external services touched.",
    )
    notable_functions: list[str] = Field(
        default_factory=list,
        description="Names of the most important functions defined.",
    )


class ExcelFileSummary(BaseModel):
    """What the .xlsx file looks like and apparently contains."""

    sheets: list[str] = Field(default_factory=list)
    columns_per_sheet: dict[str, list[str]] = Field(default_factory=dict)
    apparent_purpose: str = Field(
        ..., description="One sentence on what this workbook is used for."
    )


class WorkflowSummary(BaseModel):
    """Combined view + clarifying questions for the human owner."""

    workflow_name: str
    purpose_paragraph: str = Field(
        ...,
        description=(
            "A single paragraph (3 to 6 sentences) describing the end-to-end "
            "purpose of this workflow."
        ),
    )
    python: PythonFileSummary
    excel: ExcelFileSummary
    clarifying_questions: list[str] = Field(
        ...,
        min_length=3,
        max_length=5,
        description="3 to 5 short questions to ask the human owner.",
    )


class WorkflowAnswers(BaseModel):
    """The human's answers, collected at CLI prompt."""

    frequency: Literal[
        "daily", "weekly", "monthly", "quarterly", "ad_hoc"
    ] = "monthly"
    owner: str = "Unknown"
    downstream_consumers: list[str] = Field(default_factory=list)
    extra_answers: dict[str, str] = Field(default_factory=dict)


class FinalDoc(BaseModel):
    """The rendered markdown documentation, ready to write to disk."""

    title: str
    overview: str
    schedule: str
    inputs_table_md: str = Field(
        ..., description="A Markdown table of inputs with columns: Name, Type, Source."
    )
    outputs_table_md: str = Field(
        ..., description="A Markdown table of outputs with columns: Name, Type, Destination."
    )
    runbook_md: str = Field(
        ...,
        description=(
            "A Markdown 'How to run this workflow' section, including any env vars, "
            "manual steps, and recovery steps if a run fails."
        ),
    )
    open_questions: list[str] = Field(default_factory=list)

    def to_markdown(self) -> str:
        """Render the full documentation as a single markdown string."""
        return f"""# {self.title}

## Overview

{self.overview}

## Schedule

{self.schedule}

## Inputs

{self.inputs_table_md}

## Outputs

{self.outputs_table_md}

## Runbook

{self.runbook_md}

## Open Questions

{chr(10).join(f"- {q}" for q in self.open_questions) if self.open_questions else "_None._"}

---

_Generated by workflow-doc-agent. Review and edit before publishing._
"""
